version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: b1d98e.xc7lglym32dqjkpb
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBNGxhWnIydW03QzJsMzZQZUFEMVVwVEFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qWXdNVEkwTWpNME5ESTVXaGNOTXpZd01USXlNak0wTkRJNVdqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQUpLd01HMVBmU1N5czdVU016dlhmUXp4SlhlMXJkVWFZYWtjCnJCVlcrM3JYbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRk5KeWNwUVc1ZXhPVW5GdQp1a1IwRjBWRWtpL3dNQVVHQXl0bGNBTkJBR2pSWUlORkRhRFBScUNOQThlbDlOMTUxQVV0Y3orSS93cTVpWTkvCldvWXd1NENEeURmTHZXV0o2UURMTWdjbnp0LzhSeHNXUjF3Q3NVUXl4cFgrUmdnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJTW0yWlZ4NXA4TUZaMW4yOTRBR3BIczdPNno2bzY3QTRLVmd0TzU5ek9lUQotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.34.0
        extraArgs:
            node-ip: 192.168.111.162
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network:
        hostname: daphne
        interfaces:
            - interface: enx00155d00cb10
              vlans:
                - addresses:
                    - 192.168.111.162/24
                  routes: []
                  vlanId: 111
                  vip:
                    ip: 192.168.111.160
                - addresses:
                    - 192.168.208.162/24
                  routes:
                    - network: 0.0.0.0/0
                      gateway: 192.168.208.1
                  vlanId: 208
              dhcp: false
        nameservers:
            - 192.168.208.70
            - 192.168.208.1
    install:
        disk: /dev/sda
        image: ghcr.io/siderolabs/installer:v1.11.0
        wipe: false
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    nodeLabels:
        node.kubernetes.io/exclude-from-external-load-balancers: ""
cluster:
    id: Et7IV1n8rCOCHDN1rPhxThqb-J_6gH6J0Ay2pPQjODo=
    secret: mN/65LTar5k7lMiJR2O3EeLnrbzblNmtnPs2Ca0sD/A=
    controlPlane:
        endpoint: https://192.168.111.160:6443
    clusterName: vixens-dev
    network:
        cni:
            name: none
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: to5m18.m5a5z0iir7f29jsp
    secretboxEncryptionSecret: odP3vmPi+haRd5Rh3Gr2v5dRkD6Sd2D9mk81ZeXAdV0=
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpRENDQVMrZ0F3SUJBZ0lRTVFnZ3dDUm5ac0dTWm84QVBwNUNJVEFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTJNREV5TkRJek5EUXlPVm9YRFRNMk1ERXlNakl6TkRReQpPVm93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCTCtVbU4ybTkyYWJGd0dLVVdQK0xIZzVyMWl0RFJhVGNtaGdmTEZtMHBxR0RPcDEzVDgvZEo5dldjekMKQUt1ekF5VzdlYUxuK2VLZmlEcXBIVGwrTjUyallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVwU3ZIQXN4UzFVa084T3NnWmhTaWo0dGIxSVV3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnTUl3WlV5dGEKUW1XVElWMSs1YXdEMlRubmlaQUtKK0hFRkRKUldEWVFSdElDSUNpQlpnRmFrY3R4dGFIWlZrYkNmdEppbmg2aQo3ZHJ5SElwdVlzd3lCMjYyCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSURwaTU2QnNvRjRFR1ZUdGZpa2ZnT0NmamY4d2VUNURoa2h5elY1VWNXSXVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFdjVTWTNhYjNacHNYQVlwUlkvNHNlRG12V0swTkZwTnlhR0I4c1diU21vWU02blhkUHo5MApuMjlaek1JQXE3TURKYnQ1b3VmNTRwK0lPcWtkT1g0M25RPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    aggregatorCA:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJZRENDQVFhZ0F3SUJBZ0lSQU5VOEROMVlJQStoTEV3ZkY2eCtYdHd3Q2dZSUtvWkl6ajBFQXdJd0FEQWUKRncweU5qQXhNalF5TXpRME1qbGFGdzB6TmpBeE1qSXlNelEwTWpsYU1BQXdXVEFUQmdjcWhrak9QUUlCQmdncQpoa2pPUFFNQkJ3TkNBQVQ3ZmdCemFoSlJLNzVncVNEaGJPQWZEeTEvZ1hyMEJXV05zR0lDTHdMZVo4bVRVOTljCk9MemsyV1NzaUZrRVNVUm41b1FYbkZrbVZhZFRLYkpPM2t5dW8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXcKSFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpIUVlEVlIwT0JCWUVGUHROWURrRzRwQVBVZnVJRElGQitLSVd0VnhrTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDCklHcDBrMEFiNTlmYUdUN2V2VzZpejFYNUs1SGhiZUNYZStqcEFrSWk0aEkxQWlFQTJnZ2xEUy9GV0orUVl4R1AKd2RCRXNLcmpaL1loRVlmbklrMjlWQjlaOVZvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1GZFM0STJ3NDlvYXpFWUhoUFJKYThQelRpMEdXRzByNTRscUJJQjhXY0hvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFKzM0QWMyb1NVU3UrWUtrZzRXemdIdzh0ZjRGNjlBVmxqYkJpQWk4QzNtZkprMVBmWERpOAo1TmxrckloWkJFbEVaK2FFRjV4WkpsV25VeW15VHQ1TXJnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    serviceAccount:
        key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBckZ0RmRtSTA1QmcrUGNSU0dPK0w3NWNROHZqdnBSZVFsRjRyaHU0OTM5azVWbTVPCmlRTHYzU2VuaXQwY2kyQmc2eHdLZFM5bnBvb2lTSEhDT0RYZEtNcUd2YzVnRUFEYVNNRzAxajVwS05DbUwvQVoKWXVSeHZNL3hlU0JkZHVBWC8vYXMxOU1aUGpwbUFBam9sREQzUU4yWFVmMytKVVdYV1RhRmNtdDFaWlFOUDBQMAp5ZGZ5RUtoQk1HMG9ZZVdwL2RSWVN4UnBINVN5OXg0TUlBYUI0V2Yvdy9aeXNTZ3dmR3k0d21sQnlxN2dNVk1xCjdjVTJ1b29SaWNPOHA0U1lFaFEvV1J3aUtTU2pYemc0UUZ6RzFLNG4xbkcxQUxUVWZ1b2RaVzdmaHkxZFlmc3cKZ1B5Sms4R1RudHdpRkxBNTAvWGw3eitZWjFxYTJSalpxWG0zbGNERFU2d3p5eWlOOTZSYmp0K3dOWS9NeTY2Mwp6amFNVUlZYlBmL3YyWDlBVm9mOUVndXkyVjF4SCt0dTJwKzgvQUkwYnFtY3hqUzRYejlsM0pzTGk4ZkNFVGpOCmg4bVJXT2svaGhqTFU5Tnlxdm1zK2ZjajNNYjRMdEhkZElFMTdDVVRsZ25vRGtibGYxd1pMOXE1VzZXSFBYYloKaFJLL0plQS91YU8yQ1Z3MVE3cVZtN29Qa3lpbzFqNzYzZnB6cWp4U3RDdWlrSUovbE5uZFl4NllYUDRLSmtHbAo2MmtFWGRVY0VuenExUERZa1IvNXpnVGhtUnRzN0hUUWpoaEFkVHZxRCtXeHVnalNSZG9QN3A5dys3RDVYNUN5CkpFTHd2VW9VTVlrVEdjUGNwWWk1NG91b1pjQUlwY0ZrWitCcWUzQWMrcUJac1ZmeWRMdXJycFVQM2hFQ0F3RUEKQVFLQ0FnQUc1MktIU1F5RGtQV0lTWmw4d25hbFhwU1pHTy9YZWZQS2Y2R29kbGxQNHI1OVYrNkpKaThYdVplSQpWRTVKQm0rblowQ0RmR1kvV1dQaGFUNGRmSW5hOFE3WDRrRCtqeHd2UXlRVVcxeGd2RWZWM24wVDFTRDVyazRtCnV3MUhYbGRUdzB5ZDJnaTJNWVpsckxXdFB1OWVmNm5JcU44QjNQRmdxMUtKMkdSVDBPdjlhMkpPSmZwZUlMRTQKeUh5UVBFLzBlUW1lMjBiUk15WitoOHQyU25Cd0tCZHFnUEFMNk5kVldwRUZoNHdSTzNORFFvaXpETDNpRjdiMwpZTm5wRDJKOGdlZGVNVVpzaGJsT0RuMVJWYTRJdForbW96Z2Irc0pTd1p1ekZROTYxWTQ2cHlKRW5tai8zRWFHCm05eDVIZXg1RVMzWVNTQzRqaHhyQXdmdjlnNU1qbDVwVHNsTnhrejBHS3hQSzlqb3RxQnBtVDdldUg1RGhIUlIKRlVuOWRodmdDd2JzeVh2N0VmcXBxKzc3SFpXTkdDRlRST2ZCcFVTaUNKdGh2RU5lVUR2UUIvSVNrM1Q1VnhUWQpOWmxlRHBSY2txek9ZUFNUQlFkOHlRZEd4eFhVcElZeGtTS1JVWG4rMXlFQ1hBREpxZ0M3eHhmNVB6c3Mrem9hCkMzYnByR2xWRU1BNGdwd0NXK201QUFDbEtlcXhDbkp1VVhMZjlRcm1IRUVGeUJLR0hQTU9RMi95eUtaSnhrSDIKZXQyaEx6YXZTYnRCNWZoaVkzbXlmOGdKcGlYNXRONG4wZ2VHTW5TYm52Yi93UGRMZWl1Tnh3SmM3OXI0WVlNdQorL3dOTjBUa0hxS3lBVGgyd29ZWEo0Q0hvWUNvc296TU9DNUFGYkM4cGsvRWpoWWZhUUtDQVFFQXpOL25vYlZQCmoyVUdYL28rbURBZ3ZvazB1ZXdLdEJHSnBkU3BOSkt6cjI0WlRhVnJ4bzFyV1ovTzBLcEMrUndkUkh1RG04ZDQKekkvK0pxU0JSdHg2OWdmb0IveTdYWnpKQXV2VWliR3UvSWxyWmxybFd2ZTFWV1R2UnBubExXWm4remNHd09uRgpVQ3ZJTkNoWVlFUS9aa0lOQkt1a0ZGNTJQakdTRUMrcUtpK2RLeGI5TFV0Nlkzamx2OHRHS09DcUhrdURUVUZpCkxiOEd1NW1UY0xxZEdmbE1VVzB3WFZPSmQ0Vnpad1N2eTlkSFJzYkgvR01xRC91MU5ILy9kT2pINXZETXNVTGsKbXdKRzVWek93TDNzaHBCZlRtaWx6VnJhaU5Sa2Q1OGFJRVJRN0hSaDB6aWl2dGtGd0VETjVPOTJBekF3Rit3UQpMRDdaMUJxR05Hb2V1UUtDQVFFQTExMy9wQytDdmxwNjVCQ1ZPT2F6dnU0cVVSQjRJT2FvQ2V1ZDExYmh6cEhHCndHd1MwVnBIb2dId2xuZmpodEltQytkcmxoQ2pTRVFra0Fxcmd4U1lEbUpPa0drdXExeStteUpDZEIzUFVIUEwKeDdOQXpCdVVDSWkvRmRoRmFMNEdva29RbVozSU8vSVdVcFZoenQ3T0NHYSt1eXdVQUNjYXlxMFZsdmR4cmlPWApYU0oyYi9KN2Zkc3hDM1A4ak1iQUxoS2ZvQ2ZmamtwU2w1MVJkS3B5MTFYV2FvbnJEVmR2cjB4cEdkeTZ4MU9GCmR4Y3hqYVFUNXYrUFNlcXVTZzB5NHpUbXlaRXN5S0pRRysxaUVJQ3I5N3ZXSXY1K3EyelUzMDJmN0w3dlNSWTUKOWZJN2JkbUMwRmZ4cXZCRTRhdXdLVUppL25wbk1HeWRVMXV1ZE1yT0dRS0NBUUI5Vk14QzVNUVRHTjVaZ0tFaQpRTzhISUxDY3ZJV2Z1c3JXSTg2UFZ0K05obkQ4U3lJdmlQd1BDL0JkUG90U0Vaemw5Qm1EQnZnalRFTlNLSGpkCmZLdk1MdklIVU5qZVg3ZW9qZFNybDROUkFsQXRnWldsbkx2VnpiV0RIMHBRQjhHOHNPRDB5dzNtQ2FLa0picEsKeWZWdS9TRXhwajd1Snd0MjZLUk9PcHFDekRYOTBrWjNteUQ0RVZHYmp5TVFoc0FMWUc2bXFFVURiMFVUSnRSSAp0aUc5YmdEK0h5bmpMZU4rdHFqdWNMT0tvOXY2dEVoTFllNnRjSEpkOTUrelNXUmhKeFpScW5ablRYRkpod2tFCmFDdDE5b1FYVjNWMnR3blJndjBqSUxXKzM0d1IydkN0WW94TTdEN1VhZENMS09LcytLR3pRTHAwRnM3ekxuYkQKUWRnaEFvSUJBSHZMVFZIcitXUS9rQm9lS2hnK0RCMzR1cHhFTWpqL1BLSVBMSGlHT1YvS3pZcjMxRTFBYnFLQwpLTy9rMUFWQU1KeHhGcGQ0MHRLTVVOUDNQaVVucGt2R1dGQ01GVVp0RmljSUoxaWxkZkJSejFYb0JKd09VaVloCnJHejdGdEtoUUNEekg5MmRJMmJKdmVrVWN0YzluUUtaUkpORVArN2lpM1RxenRrclBNNFRLVU5ndHVHY2FUMnIKeStKQWRtL1pJc2lZN2VaYVpSZGVRMkZoRFZ4WlNZL2JpRmRQRmF4aWtSRWJnK0pZellnYnkwRHNOUkNzdXIveQpNRVFWd0w5U0hPa2JGSG5TbUFKdndrcDdSZjRrYURVTFpJaFM3eTdNYlFRNmsyMjdSc0lsSTRYckNod1hoaWtLCkZDRGs0VU15dEJ6VFN5SHA2L3lhd2tnVEVCR1VMYWtDZ2dFQkFJQ2ZWWGxNb294VFRaUkpkUUFhU2FtU2tpcisKZjloVkZOak9UV2RtcjJ4TVhoRloyMVd1SGpRdlFyQW9nYTkzUXdvWlJ1eFpMRWlUNG9Oa2FqbXIybDJMZVZGaAp1UFpXbGliUHJERUFJUWhORFQveVVTQ1NUZ3Btbi9YYXQyVCtmbXFWM04wbzU0Y2JhbTk3R2xPUzF1bGVmNklWCk11UHRoTDBXQXA5Z2pxSzVXTHdxbXZQaU4raFJ6OTRxR0hJRGw4ZDJjRE4wNW9nWmtDNUNyU2dZbnkrWGxQWDUKa2oxUlB6MnZCSGduTU9SbzRtYXhaNEhwa1Z4YXBDT0hZd0dYM3NCdTZJbDhYK05TcEZqZ0xydHAwcHZPMis2MQp1cmhUYk0xWG00Y0RvUnZBOTVrb3pqNXBQVU9XSndwaWdoMGc2RVl4SWp6V0t1UmZZYmxWQ2N2NVBaaz0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.34.0
        certSANs:
            - 192.168.111.160
            - 192.168.111.160
        disablePodSecurityPolicy: true
        admissionControl:
            - name: PodSecurity
              configuration:
                apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                defaults:
                    audit: restricted
                    audit-version: latest
                    enforce: baseline
                    enforce-version: latest
                    warn: restricted
                    warn-version: latest
                exemptions:
                    namespaces:
                        - kube-system
                    runtimeClasses: []
                    usernames: []
                kind: PodSecurityConfiguration
        auditPolicy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
                - level: Metadata
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.34.0
    proxy:
        disabled: true
        image: registry.k8s.io/kube-proxy:v1.34.0
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.34.0
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
    etcd:
        ca:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmakNDQVNPZ0F3SUJBZ0lRSktrWlRCdE9LdjBNbUJ0aDBabktmekFLQmdncWhrak9QUVFEQWpBUE1RMHcKQ3dZRFZRUUtFd1JsZEdOa01CNFhEVEkyTURFeU5ESXpORFF5T1ZvWERUTTJNREV5TWpJek5EUXlPVm93RHpFTgpNQXNHQTFVRUNoTUVaWFJqWkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkxDUlhOemZSSjN2CnNXeExDWkx5SmN1SnMrQm9UOFFEcGtXSUtwYU14aEpYYjBaMk9Ia3pEajBvbUhiakpKQndQTCtsbzEyZ2hQaGcKWGgwUndjSEY4V1dqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjRApBUVlJS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVVWJIMkladG1MOVBwClVHRU9kZGFMQ3JGNEh4QXdDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBTktaclR2QTRVclNtdEZ2TUl0ZGhmcWgKbkQyTDVMbnMwYzJkTHUxTTg4UkJBaUVBczBoVm94SlpDNzB2Qmc1cXVlbmJxbGJ1NHJiNXVoRExadnZXV1ZPawp4Smc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU5xb2RaQTBwVzFtS2xNTTdGUkc4UCtRdVF5VlZYTGR2VjNSYmlhMkMwWG1vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFc0pGYzNOOUVuZSt4YkVzSmt2SWx5NG16NEdoUHhBT21SWWdxbG96R0VsZHZSblk0ZVRNTwpQU2lZZHVNa2tIQTh2NldqWGFDRStHQmVIUkhCd2NYeFpRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=

